# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bcfafed21b080aef1839c76cce1297b1"
name = "Sales reps app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,read_product_listings,read_publications,read_companies,read_customers,write_draft_orders,read_draft_orders,read_orders,read_markets"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
